# ref: https://github.com/actions/runner-images
name: amd64 Windows Bazel

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  bazel:
    strategy:
      matrix:
        runner: [windows-2022, windows-2019]
        python-version: ['3.9', '3.10', '3.11', '3.12']
      fail-fast: false # Don't cancel all jobs if one fails.
    runs-on: ${{ matrix.runner }}
    #runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check java
        run: java -version
      - name: Check mvn
        run: mvn --version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check Python
        run: python --version
      - name: Install Bazel
        run: choco install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --cxxopt="/std:c++20"
          --subcommands=true
          //ortools/... //examples/...
      - name: Test
        run: >
          bazel test
          -c opt
          --cxxopt="/std:c++20"
          --test_output=errors
          //ortools/... //examples/...
