name: CentOS

on:
  push:
    branches:
      - main
      - feature/*
      - merge*
      - fix/*
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ github.token }}
  RELEASE_CREATED: ${{ github.event_name == 'release' && github.event.action == 'created' }}

jobs:

  build:
    name: shrd=${{ matrix.shared }} extras=${{ matrix.extras }} java=${{ matrix.java }} dotnet=${{ matrix.dotnet }} python=${{ matrix.python }}-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    container: 'centos:centos7'
    env:
      XPRESS_INSTALL_DIR: xpressmp/
    strategy:
      fail-fast: false
      matrix:
        shared: [ON, OFF]
        extras: [OFF]
        include:
          - extras: OFF
            python: OFF
            java: OFF
            dotnet: OFF

    steps:
      - name: set name variables
        id: names
        run: |
          SHARED=${{ matrix.shared }}
          [ $SHARED == "ON" ] && WITH_SHARED="_shared" || WITH_SHARED="_static"
          OS="_centos7"
          APPENDIX="${OS}"
          echo "::set-output name=appendix::$APPENDIX"
          APPENDIX_WITH_SHARED="${OS}${WITH_SHARED}"
          echo "::set-output name=appendix_with_shared::$APPENDIX_WITH_SHARED"

      # Fill variable ${BRANCH_NAME}
      - uses: nelonoel/branch-name@v1.0.1

      - name: Install requirements (yum)
        run: |
          yum install -y epel-release
          yum install -y git redhat-lsb-core make wget centos-release-scl scl-utils
          yum install -y devtoolset-9
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.22.x'

      - name: Checkout OR-Tools
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .

      - name: Checkout Xpress linux
        uses: actions/checkout@v2
        with:
          repository: rte-france/xpress-mp
          path: ${{ env.XPRESS_INSTALL_DIR }}
          ref: "9.0"
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: set Xpress variables
        run: |
          cd ${{ env.XPRESS_INSTALL_DIR }}
          echo "XPRESSDIR=$PWD" >> $GITHUB_ENV
          echo "XPAUTH_PATH=$PWD/bin/xpauth.xpr" >> $GITHUB_ENV

      - name: Configure OR-Tools
        run: |
          source /opt/rh/devtoolset-9/enable
          cmake --version
          cmake -S . -B build -DBUILD_SAMPLES=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="build/install" -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DBUILD_DEPS=ON -DBUILD_PYTHON=${{ matrix.python }} -DBUILD_JAVA=${{ matrix.java }} -DBUILD_DOTNET=${{ matrix.dotnet }} -DBUILD_FLATZINC=OFF

      - name: Build OR-Tools Linux
        run: |
          source /opt/rh/devtoolset-9/enable
          cmake --build build --config Release --target all install -j4

      - name: Prepare OR-Tools install
        id: or-install
        run: |
          cd build
          ARCHIVE_NAME="ortools_cxx${{ steps.names.outputs.appendix_with_shared }}.zip"
          ARCHIVE_PATH="$PWD/${ARCHIVE_NAME}"
          zip -r $ARCHIVE_PATH ./install
          echo "::set-output name=archive_name::$ARCHIVE_NAME"
          echo "::set-output name=archive_path::$ARCHIVE_PATH"

      - name: Run xpress_interface unittests
        run: |
          cd build
          ctest -V -C Release -R 'cxx_unittests_xpress_interface'
      - name: Run specific cpp tests
        run: |
          cd build
          ctest -V -C Release -R 'cxx_cpp_linear_programming'
      - name: Run other cpp tests
        run: |
          cd build
          ctest --output-on-failure -C Release -R cxx_cpp -E 'cxx_cpp_linear_programming'

      - name: Upload OR-Tools install artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.or-install.outputs.archive_name }}
          path: ${{ steps.or-install.outputs.archive_path }}

  publish_asset:
    name: Publish release assets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        if: ${{ env.RELEASE_CREATED == 'true' }}
        uses: actions/download-artifact@v3

      - name: Publish assets
        if:  ${{ env.RELEASE_CREATED == 'true' }}
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["*/*.zip"]'
