name: Windows Java Dotnet

on:
  push:
    branches:
      - main
      - feature/*
      - merge*
      - fix/*
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Windows java and dotnet
    runs-on: windows-latest
    env:
      XPRESSDIR: ${{ github.workspace }}\xpressmp
      XPRESS: ${{ github.workspace }}\xpressmp\\bin
      XPAUTH_PATH: ${{ github.workspace }}\xpressmp\bin\xpauth.xpr
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install SWIG 4.1.1
        run: |
          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.1.1.zip","swigwin-4.1.1.zip");
          Expand-Archive .\swigwin-4.1.1.zip .;
          echo "$((Get-Item .).FullName)/swigwin-4.1.1" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Remove-Item .\swigwin-4.1.1.zip
      - name: Check swig
        run: swig -version

      - name: Set-up Xpress with pip
        shell: bash
        run: |
          python -m pip install --no-cache-dir "xpress>=9.0,<9.1"
          XPRESS_DIR="${{ env.pythonLocation }}\Lib\site-packages\xpress"
          cp -r $XPRESS_DIR/lib $XPRESS_DIR/bin
          echo "XPRESSDIR=$XPRESS_DIR" >> $GITHUB_ENV
          echo "XPAUTH_PATH=$XPRESS_DIR\license\community-xpauth.xpr" >> $GITHUB_ENV
          echo "$XPRESS_DIR/bin" >> $GITHUB_PATH

      - name: Check cmake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_JAVA=ON
          -DBUILD_DOTNET=ON
          -DBUILD_CXX_SAMPLES=OFF
          -DBUILD_SAMPLES=OFF
          -DCMAKE_INSTALL_PREFIX="install"
          -DBUILD_FLATZINC=OFF

      - name: Build
        run: >
          cmake --build build 
          --config Release 
          --target ALL_BUILD
          -v -j2

      - name: Tests not xpress
        working-directory: ./build/
        run: >
          ctest -C Release 
          --output-on-failure 
          -E "xpress"

      - name: Check xpress installation
        shell: bash
        run: |
          echo "ls -l $XPRESSDIR"
          ls -l $XPRESSDIR
          echo "ls -l $XPRESSDIR/bin"
          ls -l $XPRESSDIR/bin
          echo "ls -l $XPRESSDIR/lib"
          ls -l $XPRESSDIR/lib
          echo $XPAUTH_PATH
          cat $XPAUTH_PATH

      - name: Tests xpress
        working-directory: ./build/
        run: |
          $env:XPRESSDIR
          Get-ChildItem -Path $env:XPRESSDIR
          ctest -V -C Release --output-on-failure -R "xpress"

      - name: set name variables
        id: names
        shell: bash
        run: |
          SHARED=${{ matrix.shared }}
          [ $SHARED == "ON" ] && WITH_SHARED="_shared" || WITH_SHARED="_static"
          OS="_windows-latest"
          APPENDIX="${OS}"
          echo "::set-output name=appendix::$APPENDIX"
          APPENDIX_WITH_SHARED="${OS}${WITH_SHARED}"
          echo "::set-output name=appendix_with_shared::$APPENDIX_WITH_SHARED"

      - name: is release created
        shell: bash
        run: |
          release_created=${{ github.event_name == 'release' && github.event.action == 'created' }}
          echo "RELEASE_CREATED=$release_created" >> $GITHUB_ENV

      - name: Get release
        if: ${{ env.RELEASE_CREATED == 'true' }}
        id: get_release
        uses:
          bruceadams/get-release@v1.2.3

      - name: install zip
        shell: cmd
        run: |
          choco install zip --no-progress

      - name: prepare OR-Tools jar
        id: jar
        shell: bash
        run: |
          cd ./build/java
          MY_DIR="ortools_java${{ steps.names.outputs.appendix }}"
          mkdir ${MY_DIR}
          cp ortools-*/target/*.jar "${MY_DIR}"
          ARCHIVE_NAME="${MY_DIR}.zip"
          ARCHIVE_PATH="${{ github.workspace }}/build/${ARCHIVE_NAME}"
          zip -r "${ARCHIVE_PATH}" "${MY_DIR}"
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT

      - name: Upload OR-Tools jar artifact
        if: ${{ env.RELEASE_CREATED == 'false'}}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.jar.outputs.archive_name }}
          path: ${{ steps.jar.outputs.archive_path }}
      - name: Publish OR-Tools jar asset
        if:  ${{ env.RELEASE_CREATED == 'true' }}
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.jar.outputs.archive_path }}
          asset_name: ${{ steps.jar.outputs.archive_name }}
          asset_content_type: application/zip

      - name: prepare OR-Tools dotnet
        id: dotnet
        shell: bash
        run: |
          cd ./build/dotnet/packages/
          MY_DIR="ortools_dotnet${{ steps.names.outputs.appendix }}"
          mkdir ${MY_DIR}
          cp Google.OrTools.*.nupkg "${MY_DIR}"
          cp Google.OrTools.runtime.*.nupkg "${MY_DIR}"
          ARCHIVE_NAME="${MY_DIR}.zip"
          ARCHIVE_PATH="${{ github.workspace }}/build/${ARCHIVE_NAME}"
          zip -r "${ARCHIVE_PATH}" "${MY_DIR}"
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT

      - name: Upload OR-Tools dotnet artifact
        if: ${{ env.RELEASE_CREATED == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.dotnet.outputs.archive_name }}
          path: ${{ steps.dotnet.outputs.archive_path }}
      - name: Publish OR-Tools dotnet asset
        if:  ${{ env.RELEASE_CREATED == 'true' }}
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.dotnet.outputs.archive_path }}
          asset_name: ${{ steps.dotnet.outputs.archive_name }}
          asset_content_type: application/zip
